### ISSUE TITLE
Post/pages

### ISSUE THREAD

**Issue by AnaH-1907** [WildCodeSchool/healthymood-back#11]
**User storie**

En tant que Admin je souhaiterais  Ajouter/lire/modifier/supprimer/

**Condition d'acceptation**

- Ajouter librement des pages

**Scénario de test**

**Comment by Astarosa** [comment]
@ComicScrip nouvelle version qui ne gère plus le user id en dur dans le client. Il est maintenant géré directement dans l'api. Voir la branche de l'api generic_pages.
